import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/Home.module.css'

const Post = () => {
  const router = useRouter()
  const { slug } = router.query
  console.log(slug)
  const ListaNumeros =[ 1,2,3,4,5,6,7,8,9,10]

  return (
    <div className={styles.container}>
      <Head>
        <title>Matemática</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.App}>
        <div className={styles.Tabuada}>
            {
              ListaNumeros.map(nivel => 
                <div key={nivel} className={styles.LinhaTabuada}>
                  <div className={styles.TabuadaCard}>{slug}</div>
                  x
                  <div className={styles.TabuadaCard}>{nivel}</div>
                  = 
                  <input id={nivel} type='number'/>
                </div>)
            }
        </div>
        <button>Verificar </button>

      </main>

      <footer className={styles.footer}>
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Hugo Gama
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  
  )
}

export default Post